---
title: "capstone"
author: "Lugita Analia"
date: "1/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE) 
```

# Import Library
```{r}
library(shiny)
library(shinydashboard)
library(dplyr)
library(lubridate)
```

```{r}
data <- read.csv("covid.csv",fileEncoding = 'UTF-8-BOM')
data
```
```{r}
covid <- data %>% 
  select(-c("Growth.Factor.of.New.Deaths","Growth.Factor.of.New.Cases","Total.Rural.Villages","Total.Urban.Villages",
            "Total.Cities","City.or.Regency","Total.Cases","Total.Deaths","Total.Recovered","Total.Active.Cases")) %>% 
  mutate(Dates = as.Date(Dates, format = "%m-%d-%Y"),
         Island = replace(Island, Island=="","Kalimantan"))
covid
unique(covid$Island)
```
```{r}
covid_daily <- covid %>%
  group_by(Dates) %>%
  summarise(Total_Cases = sum(New.Cases),
            Total_Death = sum(New.Deaths),
            Total_Recover = sum(New.Recovered)) %>% 
  mutate(Cumulative_Case = cumsum(Total_Cases),
         Cumulative_Death = cumsum(Total_Death),
         Cumulative_Recover = cumsum(Total_Recover),
         Active_Case = Cumulative_Case-Cumulative_Death-Cumulative_Recover,
         Month = month(Dates, label = TRUE, abbr = FALSE))
covid_daily
```

