---
title: "covid"
author: "Lugita Analia"
date: "12/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE) 
```


#Import Library
```{r}
library(shiny)
library(shinydashboard)
library(tidyverse)
library(glue)
library(scales)
library(DT)
library(plotly)
library(lubridate)
library(dplyr)
library(anytime)
library(RColorBrewer)
library(leaflet)
library(ggplot2)
```

```{r}
data <- read.csv("covid.csv")
data
```
```{r}
covid <- data %>% 
  rename(Date = ï..Date) %>% 
  select(-c("Growth.Factor.of.New.Deaths","Growth.Factor.of.New.Cases","Total.Rural.Villages","Total.Urban.Villages",
            "Total.Cities","City.or.Regency","Total.Cases","Total.Deaths","Total.Recovered","Total.Active.Cases")) %>% 
  mutate(Date = ymd(anytime::anydate(Date)),
         Month = month(Date, label = TRUE, abbr = FALSE), 
         Day = lubridate::day(Date),
         Island = replace(Island, Island=="","Kalimantan")
  )
covid

# colsums(is.na(covid))
# covid[covid$location=="indonesia"]
# dim(covid)
```
```{r}
covid.island <- data %>% 
  rename(Date = ï..Date) %>% 
  select(-c("Growth.Factor.of.New.Deaths","Growth.Factor.of.New.Cases","Total.Rural.Villages","Total.Urban.Villages",
            "Total.Cities","City.or.Regency","Total.Cases","Total.Deaths","Total.Recovered","Total.Active.Cases")) %>%
  mutate(Date = ymd(anytime::anydate(Date)),
         Month = lubridate::month(Date), 
         Day = lubridate::day(Date),
         Island = replace(Island, Island=="","Kalimantan")
         )
covid.island
```


```{r}
covid.atDate <- covid %>% 
    filter(Date <= max(Date)) %>% 
    select("Longitude", "Latitude")
leaflet(data = covid.atDate) %>% 
      addTiles() %>%
      addCircleMarkers(col = "maroon", 
                       fillOpacity = 1, 
                       radius = 5,
                       stroke = TRUE,
                       clusterOptions = markerClusterOptions(
                         maxClusterRadius=35, disableClusteringAtZoom=14
                       )
      )
```


#Jumlah total harian
```{r}
covid_daily <- covid %>%
  group_by(Date) %>%
  summarise(Total.Cases = sum(New.Cases),
            Total.Death = sum(New.Deaths),
            Total.Recover = sum(New.Recovered)) %>% 
  mutate(Cum.Cases = cumsum(Total.Cases),
         Cum.Death = cumsum(Total.Death),
         Cum.Recover = cumsum(Total.Recover),
         active.case = Cum.Cases-Cum.Death-Cum.Recover,
         Month = month(Date, label = TRUE, abbr = FALSE))
covid_daily
```
```{r}
covid_month <- covid %>% 
  filter(Month=="March")
covid_month
```


```{r}
covid_island <- covid %>%
  filter(Month=="March") %>% 
  group_by(Island) %>%
  summarise(Total.Cases = sum(New.Cases),
            Total.Death = sum(New.Deaths),
            Total.Recover = sum(New.Recovered))
covid_island
```
```{r}
data.agg3 <- covid_island %>% 
  select(Island,Total.Cases)
data.agg3
```

```{r}
plot_ranking <- data.agg3 %>% 
  ggplot(aes(x = value, 
             y = reorder(Island,value),
             )) +
  geom_col(fill = "dodgerblue4")
plot_ranking
```


```{r}
plot3 <- covid_island %>% 
  ggplot(aes(Total.Cases))+
  geom_bar()
plot3
```

```{r}
covid_island <- covid %>%
  filter(Month=="March") %>% 
  group_by(Island) %>%
  summarise(Total.Cases = sum(New.Cases),
            Total.Death = sum(New.Deaths),
            Total.Recover = sum(New.Recovered))
covid_island
```

```{r}
covid_island <- covid %>%
  filter(Month=="March") %>% 
  group_by(Island) %>%
  summarise(Total.Cases = sum(New.Cases),
            Total.Death = sum(New.Deaths),
            Total.Recover = sum(New.Recovered))

data.agg3 <- covid_island %>% 
  select("Island","Total.Cases","Total.Death","Total.Recover") %>% 
  gather(key = "variable", value = "value", -Island)

```
```{r}
covid_island <- covid %>%
  filter(Month=="March") %>% 
  group_by(Island) %>%
  summarise(Total.Cases = sum(New.Cases),
            Total.Death = sum(New.Deaths),
            Total.Recover = sum(New.Recovered))

data.agg3 <- covid_island %>% 
  select("Island","Total.Cases","Total.Death","Total.Recover") %>% 
  gather(key = "variable", value = "value", -Island)
plot3 <- data.agg3 %>% 
  ggplot(aes(Island, value)) + 
  geom_col(aes(fill = variable), position = "dodge")+
  scale_fill_manual(values=c("#153E7E","red","#6698FF"))+
  theme_minimal()
```


```{r}
plot3 <- data.agg3 %>% 
  ggplot(aes(x = Island, y=value)) + 
  geom_bar(aes(color = variable)) #+ 
  # scale_color_manual(values = c("red","black","blue")) +
  # theme_light()+
  # ggtitle("Kurva Evolusi Kasus Covid")
plot3
#ggplotly(plot3)
```


```{r}
g <- ggplot(mpg, aes(class))
# Number of cars in each class:
g + geom_bar()
```


```{r}
data.agg1 <- covid_daily %>% 
  select("Date","active.case","Cum.Cases","Cum.Death","Cum.Recover") %>% 
  gather(key = "variable", value = "value", -Date)
data.agg1
```

```{r}
# data.agg1 <- covid_daily %>% 
#   select("Date","active.case","Cum.Cases","Cum.Death","Cum.Recover") %>% 
#   gather(key = "variable", value = "value", -Date)

plot1 <- data.agg1 %>% 
  ggplot(aes(x = Date, y=value)) + 
  geom_line(aes(color = variable, linetype = variable)) + 
  scale_color_manual(values = c("red","orange","black", "blue")) +
  theme_light()+
  ggtitle("Kurva Evolusi Kasus Covid")

ggplotly(plot1)
  
#ggplot(covid_daily, aes(Date, Cum.Cases))
```
```{r}
plot1 <- data.agg1 %>% 
  ggplot(aes(x = Date, y=value)) + 
  geom_line(aes(color = variable, linetype = variable)) + 
  scale_color_manual(values = c("red","orange","black", "blue")) +
  theme_light()+
  ggtitle("Kurva Evolusi Kasus Covid")

ggplotly(plot1)
```

```{r}
covid <- data %>% 
  rename(Date = ï..Date) %>% 
  select(-c("Growth.Factor.of.New.Deaths","Growth.Factor.of.New.Cases","Total.Rural.Villages","Total.Urban.Villages",
            "Total.Cities","City.or.Regency","Total.Cases","Total.Deaths","Total.Recovered","Total.Active.Cases")) %>% 
  mutate(Date = ymd(anytime::anydate(Date)),
         Month = month(Date, label = TRUE, abbr = FALSE), 
         Day = lubridate::day(Date),
         Island = replace(Island, Island=="","Kalimantan")
  )
unique(covid$Month)
```


```{r}
covid.atDate <- covid %>% 
  filter(Date<="2020-03-10")
covid.atDate
```
```{r}
#unique(covid$Location)
covid.island <- covid %>% 
  filter(Island=="Jawa") #%>% 
  #group_by(Location)
covid.island
```
```{r}
covid_agg1
covid %>% 
  group_by()
ggplot(economics, aes(date, unemploy))
```



```{r}
sliderInput("timeSlider", "Select Date:",
                  min = min(covid_daily$Date), 
                  max = max(covid_daily$Date),
                  value = max(covid_daily$Date),
                  # pre = "$", sep = ",",
                  width      = "100%",
                  timeFormat = "%Y.%m.%d",
                  animate = animationOptions(loop = TRUE))
```


```{r}
fluidRow(valueBox(covid_daily$Cum.Cases[covid_daily$Date==covid_daily$Date[100]],
                 "Confirmed",
                 icon = icon("credit-card"),
                 color = "red"),
        valueBox(covid_daily$Cum.Recover[covid_daily$Date==covid_daily$Date[100]],
                 "Recoveries",
                 icon = icon("address-card"),
                 color = "green"),
        valueBox(round(covid_daily$Cum.Death[covid_daily$Date==covid_daily$Date[100]],
                 "Deceased",
                 icon = icon("adjust"),
                 color = "blue"))
```





```{r}
Points <- covid %>% 
  select("Longitude","Latitude")

covid.atDate <- covid %>% 
  filter(Date<="2020-06-10") %>% 
  select("Longitude","Latitude")

# web map
map <- 
  leaflet(data = covid.atDate) %>% 
  addTiles() %>%
  addCircleMarkers(col = "maroon", 
                   fillOpacity = 1, 
                   radius = 5,
                   stroke = TRUE,
                   clusterOptions = markerClusterOptions(
                     maxClusterRadius=35, disableClusteringAtZoom=14
                   )) 
#Point
map

install.packages("htmltools")
```


```{r}
leaflet(covid.atDate) %>% addTiles() %>% addMarkers(
  clusterOptions = markerClusterOptions()
)
```
```{r}
pal <- colorFactor(c("yellow","blue", "red"), domain = c("New.Cases", "New.Deaths","New.Recovered"))

leaflet(covid.atDate) %>% addTiles() %>%
  addCircleMarkers(
    radius = ~ifelse(type == "ship", 6, 10),
    color = ~pal(type),
    stroke = FALSE, fillOpacity = 0.5
  )
```








